user:
  file_path: "C:/Users/u47455/PycharmProjects/pythonProjectUserList/users.db"
  data:
    - username: ""
      email: ""
      age: ""
  queries:
    create_table: "CREATE TABLE IF NOT EXISTS user (username TEXT PRIMARY KEY, email TEXT, age TEXT)"
    insert: "INSERT INTO user (username, email, age) VALUES (?, ?, ?)"
    update: "UPDATE user SET email = ?, age = ? WHERE username = ?"
    delete: "DELETE FROM user WHERE username = ?"
    select: "SELECT * FROM user"

grocery:
  file_path: "C:/Users/u47455/PycharmProjects/pythonProjectUserList/grocery.db"
  data:
    - id: ""
      name: ""
      price: ""
  queries:
    create_table: "CREATE TABLE IF NOT EXISTS grocery (id TEXT PRIMARY KEY, name TEXT, price TEXT)"
    insert: "INSERT INTO grocery (id, name, price) VALUES (?, ?, ?)"
    update: "UPDATE grocery SET name = ?, price = ? WHERE id = ?"
    delete: "DELETE FROM grocery WHERE id = ?"
    select: "SELECT * FROM grocery"

